POST  http://localhost:3001/api/usuario/
Content-Type: application/json

{
    "nombre" : "Julia",
    "correo" : "julia@gmail.com",
    "telefono": "62343535",
    "fotoPerfil": "https://example.com/foto.jpg",
    "fechaNacimiento": "1990-05-15",
    "contraseña": "julita",
    "dni": "78654934U",
    "genero": "MUJER"
}