POST  http://localhost:3001/api/usuario/
Content-Type: application/json

{
    "nombre" : "Jesus",
    "correo" : "jesuspru@gmail.com",
    "telefono": "654321123",
    "fotoPerfil": "https://example.com/foto.jpg",
    "fechaNacimiento": "1990-05-15",
    "contraseña": "jesuss",
    "dni": "45634590A",
    "genero": "HOMBRE"
}