POST  http://localhost:3001/api/usuario/
Content-Type: application/json

{
    "nombre" : "Julio",
    "correo" : "julio123@gmail.com",
    "telefono": "623435361",
    "fotoPerfil": "https://example.com/foto.jpg",
    "fechaNacimiento": "1990-05-15",
    "contraseña": "julito",
    "dni": "78654934D",
    "genero": "HOMBRE"
}