POST http://localhost:3001/api/tareas
Content-Type: application/json

{
    "nombre": "Captar nuevos clientes para Sevilla Technology",
    "prioridad": "ALTA",
    "fechaInicio": "2025-03-10",
    "fechaVencimiento": "2025-05-05",
    "estadoTarea": false,
    "usuario": "69a6bd223cdc7aa584d5fe82",
    "corporacion": "69af0b80f90c821110c52cdc"
}