POST http://localhost:3001/api/mensajes
Content-Type: application/json

{
    "contenido": "Hola bienvenidos al grupo",
    "chat": "69af0b80f90c821110c52cde",
    "usuario": "69a6bd223cdc7aa584d5fe82"
}